#!/bin/bash

SETRUN_ARGS="$@"
#Default Values
molecule="benzene"
polymorph_list="p1"
ty="nma"
nummol="4"
hinge=""
runfiles="~/runfiles_HA"



#options passed in from the users
while getopts "p:m:t:n:h:" opt; do
        case $opt in
        p )
                polymorph_list=$OPTARG
                ;;
        m )
                molecule=$OPTARG
                ;;
        t )
                ty=$OPTARG
                ;;
        n )
                nummol=$OPTARG
                ;;
        h )
                hinge=$OPTARG
                ;;
        esac
done

for polymorph_num in $polymorph_list; do
runname=""



#copy all requisite files
cp ${runfiles}/QHAsubmit_cluster.slurm ./${hinge}.slurm
cp ${runfiles}/dftd3.dat ./
cp ${runfiles}/GTH_BASIS_SETS ./
cp ${runfiles}/GTH_POTENTIALS ./
cp ${runfiles}/KIND_BASIS_POTENTIAL.inc ./
cp ${runfiles}/${ty}.inp ./${hinge}.inp
cp ${runfiles}/POTENTIAL_DCACP_BLYP ./

#
pdbfile="${hinge}.pdb"
sed -i "s/POLY/${runname}/g" ${hinge}.inp
##replace structure file
sed -i "s/COORDFILE/${pdbfile}/g" ${hinge}.inp
#
##replace box vectors and angles
bv1=$( less ${pdbfile} | grep "CRYST1" | awk '{print $2}' )
bv2=$( less ${pdbfile} | grep "CRYST1" | awk '{print $3}' )
bv3=$( less ${pdbfile} | grep "CRYST1" | awk '{print $4}' )
ba1=$( less ${pdbfile} | grep "CRYST1" | awk '{print $5}' )
ba2=$( less ${pdbfile} | grep "CRYST1" | awk '{print $6}' )
ba3=$( less ${pdbfile} | grep "CRYST1" | awk '{print $7}' )
#
sed -i "s/AAA/${bv1}/g" ${hinge}.inp
sed -i "s/BBB/${bv2}/g" ${hinge}.inp
sed -i "s/CCC/${bv3}/g" ${hinge}.inp
sed -i "s/ANGLE1/${ba1}/g" ${hinge}.inp
sed -i "s/BETA/${ba2}/g" ${hinge}.inp
sed -i "s/GAMMA/${ba3}/g" ${hinge}.inp
#
#
#fix slurm file
sed -i "s/INPUT/${hinge}.inp/g" ${hinge}.slurm
sed -i "s/OUTPUT/${hinge}.out/g" ${hinge}.slurm
cd ..
#
done
#
